language: c
sudo: false

cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env:
      - RESOLVER_FLAG="--stack-yaml stack.yaml"
      - BUILD_PKGS=""
      - TEST_PKGS=""
    addons: {apt: {packages: [libgmp-dev]}}

  - env:
      - RESOLVER_FLAG="--stack-yaml lts-11.yaml"
      - BUILD_PKGS=""
      - TEST_PKGS=""
    addons: {apt: {packages: [libgmp-dev]}}

  - env:
      - RESOLVER_FLAG="--stack-yaml lts-10.yaml"
      - BUILD_PKGS=""
      - TEST_PKGS=""
    addons: {apt: {packages: [libgmp-dev]}}

  - env:
      - RESOLVER_FLAG="--stack-yaml lts-9.yaml"
      - BUILD_PKGS=""
      - TEST_PKGS=""
    addons: {apt: {packages: [libgmp-dev]}}

  - env: 
      - RESOLVER_FLAG="--stack-yaml lts-8.yaml"
      - BUILD_PKGS=""
      - TEST_PKGS=""
    addons: {apt: {packages: [libgmp-dev]}}

  - env: 
      - RESOLVER_FLAG="--stack-yaml lts-7.yaml"
      - BUILD_PKGS=""
      - TEST_PKGS=""
    addons: {apt: {packages: [libgmp-dev]}}

  - env: 
      - RESOLVER_FLAG="--stack-yaml lts-6.yaml"
      - BUILD_PKGS=""
      - TEST_PKGS="validity validity-bytestring validity-containers validity-text validity-time validity-uuid genvalidity genvalidity-property"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: 
      - RESOLVER_FLAG="--stack-yaml lts-3.yaml"
      - BUILD_PKGS=""
      - TEST_PKGS="validity validity-bytestring validity-containers validity-text validity-time validity-uuid genvalidity genvalidity-property"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: 
      - RESOLVER_FLAG="--stack-yaml lts-2.yaml"
      - BUILD_PKGS=""
      - TEST_PKGS="validity validity-bytestring validity-containers validity-text validity-time validity-uuid genvalidity"
    addons: {apt: {packages: [libgmp-dev]}}

  # Nightly builds are allowed to fail
  - env: 
      - RESOLVER_FLAG="--resolver nightly"
      - BUILD_PKGS=""
      - TEST_PKGS=""
    addons: {apt: {packages: [libgmp-dev]}}

  allow_failures:
    - env:
      - RESOLVER_FLAG="--resolver nightly"
      - BUILD_PKGS=""
      - TEST_PKGS=""

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack

install:
- stack +RTS -N2 -RTS setup $RESOLVER_FLAG
- stack +RTS -N2 -RTS build --only-snapshot $RESOLVER_FLAG

script:
- git --version
- stack --version
- stack --no-terminal $RESOLVER_FLAG build --haddock $BUILD_PKGS
- stack --no-terminal $RESOLVER_FLAG test $TEST_PKGS
