name: genvalidity-path
version: '0.3.0.0'
synopsis: GenValidity support for Path
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
library:
  source-dirs: src
  exposed-modules:
  - Data.GenValidity.Path
  dependencies:
  - base >=4.7 && <5
  - validity-path >=0.3 && <0.4
  - genvalidity >=0.5 && <0.6
  - path >=0.5 && <0.7
  - QuickCheck

tests:
  genvalidity-path-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - base
    - genvalidity-path
    - hspec
    - genvalidity-hspec
    - path

benchmarks:
  genvalidity-path-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - base
    - genvalidity-path
    - criterion
    - path
    - QuickCheck
    - genvalidity
