name: validity-path
version: '0.2.0.2'
synopsis: Validity instances for Path
description: Please see README.md
category: Validity
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base >=4.7 && <5
- validity >=0.4 && <0.5
- path >=0.5 && <0.7
- filepath >=1.3 && <1.5
library:
  source-dirs: src
  exposed-modules:
  - Data.Validity.Path

tests:
  validity-path-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - hspec
    - validity-path
    - genvalidity-hspec

