name: genvalidity-hspec-aeson
version: '0.2.0.0'
synopsis: Standard spec's for aeson-related instances
description: Standard spec's for aeson-related Instances
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
homepage: http://cs-syd.eu
dependencies:
- hspec

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Test.Validity.Aeson
  dependencies:
  - base >=4.9 && <=5
  - genvalidity-hspec >=0.6 && <0.7
  - genvalidity >=0.5 && <0.6
  - aeson
  - QuickCheck
  - deepseq >=1.4 && <1.5
  - bytestring

tests:
  genvalidity-hspec-aeson-doctests:
    main: DocTest.hs
    source-dirs: doctest
    ghc-options: -threaded
    dependencies:
    - base
    - doctest >=0.11 && <0.14
    - genvalidity-hspec-aeson
  genvalidity-hspec-aeson-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - aeson
    - base
    - genvalidity
    - genvalidity-aeson
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - text
