name: genvalidity-aeson
version: '0.2.0.0'
synopsis: GenValidity support for aeson
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- aeson

library:
  source-dirs: src
  exposed-modules:
  - Data.GenValidity.Aeson
  dependencies:
  - base <5
  - QuickCheck
  - genvalidity >=0.5 && <0.6
  - genvalidity-scientific >=0.2 && <0.3
  - genvalidity-text >=0.5 && <0.6
  - genvalidity-unordered-containers >=0.2 && <0.3
  - genvalidity-vector >=0.2 && <0.3
  - validity >=0.5 && <0.6
  - validity-aeson >=0.2 && <0.3

tests:
  genvalidity-aeson-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >=4.9 && <=5
    - genvalidity
    - genvalidity-hspec
    - genvalidity-aeson
    - hspec
