name: genvalidity-property
version: '0.2.0.0'
synopsis: Standard properties for functions on `Validity` types
description: Standard properties for functions on `Validity` types
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

library:
  source-dirs: src
  exposed-modules:
  - Test.Validity.Functions
  - Test.Validity.Functions.CanFail
  - Test.Validity.Functions.Equivalence
  - Test.Validity.Functions.Idempotence
  - Test.Validity.Functions.Inverse
  - Test.Validity.Functions.Validity
  - Test.Validity.GenValidity.Property
  - Test.Validity.Operations
  - Test.Validity.Operations.Associativity
  - Test.Validity.Operations.Commutativity
  - Test.Validity.Operations.Identity
  - Test.Validity.Property
  - Test.Validity.Property.Utils
  - Test.Validity.Relations
  - Test.Validity.Relations.Antireflexivity
  - Test.Validity.Relations.Antisymmetry
  - Test.Validity.Relations.Reflexivity
  - Test.Validity.Relations.Symmetry
  - Test.Validity.Relations.Transitivity
  - Test.Validity.Shrinking.Property
  - Test.Validity.Types
  dependencies:
  - base >=4.7 && <5
  - validity >=0.5 && <0.6
  - genvalidity >=0.5 && <0.6
  - QuickCheck
  - hspec >=2.1 && <2.5

tests:
  genvalidity-property-doctests:
    main: DocTest.hs
    source-dirs: doctest
    ghc-options: -threaded
    dependencies:
    - base
    - doctest >=0.9 && <0.14
    - genvalidity-property
    - directory >=1.2 && <1.4
    - filepath >=1.3 && <1.5
