name: genvalidity-containers
version: '0.3.0.0'
synopsis: GenValidity support for containers
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- containers

library:
  source-dirs: src
  exposed-modules:
  - Data.GenValidity.Containers
  - Data.GenValidity.Map
  - Data.GenValidity.Tree
  - Data.GenValidity.Sequence
  - Data.GenValidity.Set
  dependencies:
  - base <5
  - QuickCheck
  - genvalidity >=0.5 && <0.6
  - validity >=0.5 && <0.6
  - validity-containers >=0.3 && <0.4

tests:
  genvalidity-containers-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >=4.9 && <=5
    - genvalidity
    - genvalidity-containers
    - genvalidity-hspec
    - hspec >=2.2 && <2.5
