name: validity-uuid
version: '0.0.0.0'
synopsis: Validity instances for uuid
description: Please see README.md
category: Web
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base >=4.7 && <5
- validity >=0.5 && <0.6
- uuid
library:
  source-dirs: src
  exposed-modules:
  - Data.Validity.UUID
